### ISSUE TITLE
Greg Young - The art of destroying software 43m

### ISSUE THREAD

**Issue by crccheck** [TabbedOut/learninglunch#46]
https://vimeo.com/108441214

**Comment by nosamanuel** [comment]
We watched this... I recommend just reading the notes instead because the talk is very poorly organized and there's a lot of repetition.

https://maximilianhoffmann.com/talks/programming/the-art-of-destroying-software

**Comment by crccheck** [comment]
Too late! Agreed. It's a drawn out lightning talk.
